disabledraw;
disablehistory 0x0041;

if (selecting == 1){
  // git blame -L startlineno, endlinenoファイル名
  $git = "git.exe blame -L " + str(seltopy) + "," + str(selendy) + " ";
}else{
  // git blame ファイル名
  $git = "git.exe blame ";
}

$$cmd = $git + filename2;
$$file = getenv("TMP") + "\\" + basename2 + "_blame" + "." + filetype;
run $$cmd + " > " + $$file;
openfile "/r " + $$file;

// 実行コマンド表示する
##mode = 0;
if (tabmode) {
  ##mode = 3;
}
title $$cmd,##mode;
title -1,##mode;
endmacro;
